# -*- coding: utf-8 -*-
"""time vs n .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11O3W2cZT-fGTs5Qx-Z-jdN_5XZpb4eHt
"""

import numpy as np
import matplotlib.pyplot as plt

n_values = np.arange(1, 101)  # Replace 101 with your desired maximum 'n'
runtimes = 1 + n_values**2   # The polynomial curve T(n) = 1 + n^2

plt.plot(n_values, runtimes, label="T(n) = 1 + n^2")
plt.xlabel("n")
plt.ylabel("Time")
plt.legend()
plt.show()